env:
  env_type: "RoboCasa"
  robot_uids: "none"
  obs_mode: "sensor_data"

scene:
  robocasa_params: {layout_ids: 3, style_ids: 2}
  architecthor_params: {build_config_idx: 3}
  replicacad_params: {build_config_idx: 15}

simulation:
  sim_backend: "cpu"
  num_steps: 1
  seed: 42
  control_freq: 20
  sim_freq: 100

output:
  output_dir: "images/esot500syn_runs_with_distractors"
  render_mode: "rgb_array"
  save_annotations: true

lighting:
  ambient: [0.3, 0.3, 0.3]
  point_lights:
    - { position: [-1.0,  3.0,  2.2], color: [1, 1, 1] }
  directional_light:
    direction: [0.2, -0.6, -1.0]
    color: [0.6, 0.6, 0.6]
    shadow: false

camera:
  width: 512
  height: 512
  pose_p: [4.5, -4.5, 3]
  pose_g: [2, -2, 0]
  shader_pack: "rt-fast"
  motion: { type: "static" }

custom_asset:
  enable: true
  name: "cracker_box"
  visual_filepath: "~/.maniskill/data/assets/mani_skill2_ycb/models/003_cracker_box/textured.obj"
  collision_filepath: "~/.maniskill/data/assets/mani_skill2_ycb/models/003_cracker_box/collision.ply"
  initial_pose_p: [0, 0, 1]
  motion_mode: "oscillate_z"

distractor_assets:
  - enable: true
    name: "distractor_banana"
    visual_filepath: "~/.maniskill/data/assets/mani_skill2_ycb/models/011_banana/textured.obj"
    collision_filepath: "~/.maniskill/data/assets/mani_skill2_ycb/models/011_banana/collision.ply"
    initial_pose_p: [0.5, 0.2, 0.8]
    motion_mode: "static"