batch_settings:
  master_seed: 43
  num_sequences: 10
  start_index: 0

env:
  robot_uids: "none"
  obs_mode: "sensor_data"

simulation:
  sim_backend: "cpu"
  num_steps: 10
  control_freq: 20
  sim_freq: 100

output:
  # output_dir: "output/ESOT500syn_dataset"
  render_mode: "rgb_array"
  save_annotations: true

lighting:
  ambient: [0.3, 0.3, 0.3]
  point_lights:
    - { position: [-1.0,  3.0,  2.2], color: [1, 1, 1] }
    - { position: [ 0.5,  1.5,  2.2], color: [1, 1, 1] }
    - { position: [ 1.5, -0.5,  2.2], color: [1, 1, 1] }
  directional_light:
    direction: [0.2, -0.6, -1.0]
    color: [0.6, 0.6, 0.6]
    shadow: false

camera:
  width: 1280
  height: 720
  shader_pack: "rt-fast"